buildscript {
    ext.kotlin_version = '2.2.20'
    repositories {
        google()
        mavenCentral()
    }
}
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

// Subproject hook for plugin compatibility with Flutter 3.24
subprojects {
    plugins.withId("com.android.library") {
        if (!project.android.hasProperty("flutter")) {
            project.android.ext.flutter = [compileSdkVersion: 35]
        }
        project.android.compileSdkVersion 35
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
